#!/bin/sh

socket=$(echo ${DOCKER_HOST:-/var/run/docker.sock} | sed 's,unix://,,')
is_podman=$(cd "$(dirname "${socket}")" >/dev/null 2>&1 && curl -sf --unix-socket "$(basename "${socket}")" http:/localhost/version|jq -r '[.Components[]|select(.Name=="Podman Engine")]|length')
if [ -z "${is_podman}" ]; then
	echo "Cannot detect a running docker engine at ${socket}" >&2
	exit 1
fi

if [ ${is_podman} -eq 1 ]; then
	exec /usr/local/bin/podman "$@"
else
	exec /usr/local/bin/docker "$@"
fi

exit 1

