input type:keyboard {
	# See ~/.xkb/symbols/us-german-umlaut for the definition, this is based
	# on https://www.alexmoch.com/blog/sway-us-layout-with-german-umlauts/
    xkb_layout us-german-umlaut
	# Toggle using Super+Space, use Right Alt (AltGr) for german umlauts + Euro sign, compose using Right Control + AltGr
	# See xkeyboard-config(7) for all options
	xkb_options grp:win_space_toggle,lv3:ralt_switch,compose:rctrl-altgr
}
